config/routes.rb
Poiproject::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "/not_found", to: "pages#not_found", as: :not_found

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :comments

  get "pages/about"

  resources :pois do
    member do
    put "like", to: "pois#upvote"
    end
    resources :pictures
  end

  resource :poi, only: [:show], controller: :poi

  get "pages/not_found"

  root :to => redirect('/pois')

  get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/poi.rb
class Poi < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  acts_as_votable
  has_many :comments
  has_many :pictures

  accepts_nested_attributes_for :pictures

end

app/controllers/pois_controller.rb
class PoisController < ApplicationController
  before_action :set_poi, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:create, :upvote]  # Setup user permissions/roles based on the ability.rb file





  # GET /pois
  # GET /pois.json
  def index
    @poi = Poi.all

    @locations = Poi.all
    @hash = Gmaps4rails.build_markers(@locations) do |loc, marker|
      marker.lat loc.lat
      marker.lng loc.long
      marker.infowindow loc.name
    end

  end

  # GET /pois/1
  # GET /pois/1.json
  def show
    @comment = @poi.comments.build

  end

  # GET /pois/new
  def new
    @poi = Poi.new # May not need this poi creation anymore?
  end

  # GET /pois/1/edit
  def edit

  end

  # Upvote a POT
  def upvote
    @poi = Poi.find(params[:id])
    @user = User.find(params[:id])
    @poi.vote voter:@user, :duplicate => true;
    redirect_to @poi, notice: "You liked this wolf!"

  end

  # POST /pois
  # POST /pois.json
  def create
    @poi = Poi.new(poi_params)  # May not need this poi creation anymore?

    respond_to do |format|
      if @poi.save
        format.html { redirect_to @poi, notice: 'Poi was successfully created.' }
        format.json { render action: 'show', status: :created, location: @poi }
      else
        format.html { render action: 'new' }
        format.json { render json: @poi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pois/1
  # PATCH/PUT /pois/1.json
  def update
    respond_to do |format|
      if @poi.update(poi_params)
        format.html { redirect_to @poi, notice: 'Poi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @poi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pois/1
  # DELETE /pois/1.json
  def destroy
    @poi.destroy
    respond_to do |format|
      format.html { redirect_to pois_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_poi
    @poi = Poi.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def poi_params
    params.require(:poi).permit(:name, :description, :picture, :address)
  end
end

app/helpers/pois_helper.rb
module PoisHelper
end

app/views/pois/_form.html.erb
<%= form_for(@poi) do |f| %>
    <% if @poi.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@poi.errors.count, "error") %> prohibited this poi from being saved:</h2>

          <ul>
            <% @poi.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <br>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, :size=> "35x4"%>
    </div>
    <br>
    <div class="field">
      <%= f.label :picture %><br>
      <%= f.file_field :picture %>
    </div>
    <br>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    <br>
    <button class="btn btn-success">
      <input name="commit" type="submit" value="Submit" style="background:none; border-width:0px; color:white;" />
    </button>

<% end %>

app/views/pois/edit.html.erb
<div class="well bs-component" style=" width:400px; margin-left: auto; margin-right: auto; margin-top: 50px;">
    <h1>Editing poi</h1>
    <%= render 'form' %>
</div>

<div style=" width:350px; margin-left: auto; margin-right: auto; margin-top: 5px; padding-left: 5px;">
    <%= link_to 'Show', @poi %> |
    <%= link_to 'Back', pois_path %>
</div>

app/views/pois/index.html.erb
<%# Google maps JS %>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<br>

<div class="page-header">
  <%= image_tag("banner.png") %>
</div>
<br>

<% @poi.in_groups_of(3) do |group| %>
    <div class="well">

      <% group.compact.each do |poi| %>
          <%= link_to image_tag(poi.picture_url, :width => '30%'), poi %>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <% end %>
    </div>
<% end %>

<div style='width: 1170px;'>
  <div id="map" style='width: 1137px; height: 400px;'>
    <script>
        handler = Gmaps.build('Google');
        handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
            var markers = handler.addMarkers(<%=raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();

            if(navigator.geolocation)
                navigator.geolocation.getCurrentPosition(displayOnMap);

        });

        function displayOnMap(position){
            var marker = handler.addMarker({
                lat: position.coords.latitude,
                lng: position.coords.longitude,
                infowindow: "You are here!"


            });

        }
    </script>
  </div>
</div>

app/views/pois/new.html.erb
<div class="well bs-component" style=" width:350px; margin-left: auto; margin-right: auto; margin-top: 50px;">
  <h1>New poi</h1>
  <%= render 'form' %>
  <br>
</div>

<div style=" width:350px; margin-left: auto; margin-right: auto; margin-top: 5px; padding-left: 25px;">
  <button class="btn btn-primary btn-xs">
    <%= link_to 'Back', pois_path %>
  </button>
</div>

app/views/pois/show.html.erb
<%# JavaScript %>

<%# Facebook JS for sharing to Facebook %>
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=724858834225259";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<%# Google JS for sharing to Google + %>
<script type="text/javascript">
    (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/platform.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
</script>

<%# Twitter JS for tweeting to Twitter %>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
    if(!d.getElementById(id)){js=d.createElement(s);
        js.id=id;js.src=p+'://platform.twitter.com/widgets.js';
        fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
</script>

<%# Google maps JS %>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<%# END JavaScript %>

<br><br><br>

<div class="row">
  <div class="span9">
    <div id="wolfie-picture" style=" width:550px; float:left;">

      <%# Main poi picture %>
      <%= image_tag(@poi.picture_url, :width => "500") if @poi.picture.present? %>

      <br><br>
      <div class="span3">

        <%# Scrollbar filled with other POI Pictures %>
        <div class="scrolls">
          <% @poi.pictures.each_with_index do |picture, index| %>
              <% if picture.approved %>
                  <%= link_to image_tag(picture.picture, :width => "50"), ("#" + index.to_s), class: "fancybox"  %>
                  <div style="display:none;">
                    <div id="<%= index.to_s %>">
                      <%= picture.title %> <%= image_tag(picture.picture) %>
                    </div>
                  </div>
              <% end %>
          <% end %>
        </div>

        <br>

        <div style="width: 445px; float:left;">
          <%# POI Information %>
          <strong><p>Name: <%= @poi.name %></p></strong>
          <strong><p>Description: <%= @poi.description %></p></strong>

          <%# Edit and Destroy buttons for POI %>
          <% if can? :update, @poi %> <%# Check to see if the user has permission edit the poi %>
              <button class="btn btn-primary btn-xs">
                <%= link_to 'Edit', edit_poi_path(@poi) %>
              </button>
          <% end %>

          <% if can? :destroy, @poi %> <%# Check to see if the user has permission to destroy the poi %>
              <button class="btn btn-primary btn-xs">
                <%= link_to 'Destroy', @poi, confirm: 'Are you sure?', method: :delete %>
              </button>
          <% end %>

          <br><br>

          <%# Back to POI homepage button %>
          <a href="/pois"><button class="btn btn-primary btn-xs">
            Back
          </button></a>
        </div>

        <div style="width: 90px; float:left; padding-right: 25px">
          <% if user_signed_in? %>
              <% if can? :create, @comment %>
                  <div>
                    <%= link_to image_tag("upvote.png", :width => "20"), like_poi_path(@poi,@user), method: :put %>
                    <%= pluralize @poi.find_votes().size, "like" %>
                  </div>
                  <div class="g-plus" data-action="share" data-annotation="none"></div>
                  <a href="https://twitter.com/share" class="twitter-share-button" data-via="Penguinis" data-count="none">Tweet</a>
                  <div class="fb-share-button" data-href="http://172.0.0.1:3000" data-type="button"></div><br>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <br><br>

    <%# Right column of POI Show %>
    <div style='width: 500px; float:left'>
      <%# Map Code%>
      <div id="map" style='width: 500px; height: 300px;'>
        <script>

            var directionsDisplay = new google.maps.DirectionsRenderer();
            var directionsService = new google.maps.DirectionsService();

            function getPosition() {
                if(navigator.geolocation)
                    navigator.geolocation.getCurrentPosition(function(position){
                        var lat = position.coords.latitude;
                        var long = position.coords.longitude;

                        var origin      = new google.maps.LatLng(lat, long);
                        var destination = new google.maps.LatLng(<%=@poi.lat %>, <%=@poi.long %>);
                        var request = {
                            origin:      origin,
                            destination: destination,
                            travelMode:  google.maps.TravelMode.DRIVING
                        };

                        directionsService.route(request, function(response, status) {
                            if (status == google.maps.DirectionsStatus.OK) {
                                directionsDisplay.setDirections(response);
                            }
                        });
                    });
            }

            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: {id: 'map'}}, function(){
                getPosition();
                directionsDisplay.setMap(handler.getMap());
            });

        </script>
      </div>

      <br>

      <div class="well">
        <h3>Comments</h3>
      </div>

      <div style="width:20px; float:left;"><br></div>
      <div style="width:260px; float:left;">
        <% @poi.comments.each do |comment| %>
            <div>
              <strong><%= comment.user_name%></strong>
              <br />
              <p><%= comment.body %></p>
              <%# if can? :update, @comment %> <%# Check to see if the user has permission edit the comment %>
              <%# link_to 'Edit', edit_comment_path %>
              <%# end %>
              <%# if can? :destroy, comment %> <%# Check to see if the user has permission to destroy the comment %>
              <%# link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %>
              <%# end %>
            </div>
        <% end %>
      </div>

      <div style="width:220px; float:left;">
        <% if user_signed_in? %>
            <% if can? :create, @comment %>  <%# Check to see if the user has permission to post a new comment %>
                <div style="border: solid; border-color: #1C1E22; padding: 8px;">
                  <%= render 'comments/form' %>
                </div>
                <br>
                <div style="border: solid; border-color: #1C1E22; padding: 8px;">
                  <h4> Upload a picture</h4>
                  <%= form_for([@poi, @poi.pictures.build]) do |f| %>
                      <p>
                        <%= f.label :title %><br>
                        <%= f.text_field :title %>
                      </p>
                      <p>
                        <%= f.label :picture %><br>
                        <%= f.file_field :picture %>
                      </p>
                      <p>
                        <button class="btn btn-success">
                          <input type="submit" value="Post Picture" name="commit" style="background:none; border-width:0px; color:white;"></input>
                        </button>
                      </p>
                  <% end %>
                </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>