config/routes.rb
Poiproject::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "/not_found", to: "pages#not_found", as: :not_found

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :comments

  get "pages/about"

  resources :pois do
    member do
    put "like", to: "pois#upvote"
    end
    resources :pictures
  end

  resource :poi, only: [:show], controller: :poi

  get "pages/not_found"

  root :to => redirect('/pois')

  get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>The POI Project</title>
      <link rel="stylesheet" href="http://bootswatch.com/slate/bootstrap.min.css">
      <link rel="stylesheet" href="http://bootswatch.com/slate/bootstrap.css" />
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
    </head>

    <body>

        <div class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <a class="navbar-brand" href="/">
                POI APP
              </a>
            </div>

            <div id="navbar-main" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">

                <li>
                    <%= link_to "Home", pois_path %>
                </li>

                <% if can? :create, @poi %>
                    <li>
                      <%= link_to "New POI", new_poi_path %>
                    </li>
                <% end %>

                <% if can? :update, @poi %>
                    <li>
                      <%= link_to "Admin", '/admin' %>
                    </li>
                <% end %>
              </ul>

              <p class="navbar-text pull-right">
                <% if user_signed_in? %>
                    Logged in as <strong><%= current_user.email %></strong>.
                    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                <% else %>
                    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
                    <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :class => 'navbar-link' %> |
                    <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), :class => 'navbar-link' %> |
                    <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter), :class => 'navbar-link' %>
                <% end %>
              </p>
            </div>
          </div>
        </div>

        <div class="container">

          <% if notice %>
              <div class="alert alert-dismissable alert-warning">
              <strong><p class="alert alert-notice"><%= notice %></p></strong>
              </div>
          <% end %>

          <% if alert %>
              <div class="alert alert-dismissable alert-warning">
                <strong><p class="alert alert-error"><%= alert %></p></strong>
              </div>
          <% end %>

          <%= yield %>
        </div>

        <footer>
          <div class="container">
            <a href="https://www.facebook.com/codywahl">Cody Wahl</a> and Joseph Martinez - <a href="https://twitter.com/ihaterails">POI 2014</a>
            <div class="pull-right">
              <a href="#top">Back to top</a>
            </div>
          </div>

          <br>
        </footer>
    </body>
</html>